### ISSUE TITLE
Entering extremely large or small integers in the form results in an error

### ISSUE THREAD

**Issue by seanaery** [projectblacklight/blacklight_range_limit#289]
Should we impose min/max value constraints to prevent extremely large or small integers from even being submitted? Solr integer fields are 32-bit signed integers; as such the valid range is from `-2,147,483,648` to `2,147,483,647`.

If you enter a value outside those boundaries into the form you'll get a `500 Internal Server Error` with `Blacklight::Exceptions::InvalidRequest (RSolr::Error::Http - 400 Bad Request)` / `Error: Invalid Number: ### for field`.

**Comment by jrochkind** [comment]
What's the desired behavior? Should it clamp to the max/min?

**Comment by seanaery** [comment]
Not quite sure what the ideal behavior is, and I'll also add this was _not_ a show-stopper for our stakeholders that would hold up a v9 release. My institution's cases are all likely the most common use of the range limit facet (for years), where the chances a user enters a number lower than -2 billion or higher than 2 billion are virtually zero. 

I like the simplicity of using HTML5 `min` and `max` attributes client-side. We could just hardcode `min="-2147483648"` and `max="2147483647"`. Or if we want `min`/`max` to be configurable, make those the default values and add two more config options.

The validation error message/appearance would vary by browser, you can see an [example here](https://www.w3schools.com/html/tryit.asp?filename=tryhtml5_input_max_min). If we were to clamp the values server-side, the disadvantage there is we'd have to also build a way to indicate to the user that the value got clamped (or alternatively just not tell them).

I also considered trying to dynamically set the min/max for form validation based on the actual indexed data, but that would get tricky because:
1. It'd have to fetch the min/max stats for the full data set, not just the min/max of the current query, because you should be able to issue a fresh range query even from a results page where you've already provided a narrow range.
2. Even if my earliest record in the index had a year `1837` I might still want to query by century, e.g., enter `1800` to `1899`.

**Comment by jrochkind** [comment]
If we do it, it should be configurable. In case Solr or it's data types change; or someone wants to clamp manually to their actual expected data

I agree that clamping automatically to the actually existing data in the index is not a direction to pursue, for several reasons. 

I *do* like having this thing incapable of generating 500s due to user input -- including manually constructed URLs with query parameters by bots. I hate when these generate 500s, cause they show up in my logs and lead to error fatigue. 

So I'm inclined to just implement it. Config, server-side clamping without telling the user anything, plus, sure, min/max client side why not. 

Shouldn't be too hard to implement, I think. (famous last words).
