### ISSUE TITLE
Blacklight constraints don't display if only a range facet is selected

### ISSUE THREAD

**Issue by cbeer** [projectblacklight/blacklight_range_limit#5]

**Comment by cdmo** [comment]
I don't know if this is a regression of a fixed bug, or a slightly different bug, but this happened to me now using Blacklight 7, Blacklight Advanced Search and this gem.

For me it was a matter of load order in the `catalog_controller.rb` file.   `include BlacklightRangeLimit::ControllerOverride` needs to follow `include BlacklightAdvancedSearch::Controller`. Otherwise `BlacklightAdvancedSearch::Controller` appears to take the message and respond, and `BlacklightRangeLimit::ControllerOverride` doesn't get the message.

I'm happy to open a new issue if that is helpful, but I try to err on the side of not opening new issues.
